language: node_js
node_js:
- '10'
addons:
  ssh_known_hosts: 39.106.67.231
before_install:
- openssl aes-256-cbc -K $encrypted_a65247dffca0_key -iv $encrypted_a65247dffca0_iv
  -in deploy_rsa.enc -out ./deploy_rsa -d
script:
  - yarn test
before_deploy:
  - openssl rsa -in ./deploy_rsa -out ./deploy_rsa_new
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_rsa_new
  - ssh-add ./deploy_rsa_new
deploy:
  provider: script
  script: bash ./bin/deploy.sh
  on:
    branch: master
